### ISSUE TITLE
satellite sea ice concentration template

### ISSUE THREAD

**Issue by tdcwilliams** [bopen/c3s-eqc-toolbox-template#140]
### Notebook description

- can you make a template from this notebook?
- it needs to be rerun to fix the cached data which has the wrong attributes in the data
- can you give me access to the other github repo so I can get a permalink for this notebook? 

### Notebook link or upload

[satellite_sea_ice_conc_climate_change.ipynb.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/14749856/satellite_sea_ice_conc_climate_change.ipynb.zip)

### Anything else we need to know?

wp5

### Environment

wp5 environment on VM

**Comment by malmans2** [comment]
Hi @tdcwilliams,

I asked ECMWF to add you to the other repo. No answer yet.
I'm looking at your notebook right now. It's already in good shape, I'll make minor edits/optimizations.

For example, this snippet canges the dimensions from time/region to year/dayofyear/region: 
```python
ds = ds.assign_coords(
    year=("time", ds["time"].dt.year.values),
    dayofyear=("time", ds["time"].dt.dayofyear.values),
)
ds = ds.set_index(time=("year", "dayofyear")).unstack("time")
```

**Comment by tdcwilliams** [comment]
Hi @malmans2,
thanks that looks a good trick

**Comment by tdcwilliams** [comment]
Hi again @malmans2, I now have access to the other repo.

**Comment by malmans2** [comment]
Hi @tdcwilliams,

The first draft of the template is ready:
- Template: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/satellite_sea_ice_conc_climate_change.ipynb
- Notebook executed: https://gist.github.com/malmans2/8a2c0f260300b41db4fe4b2c5d2b2485

A couple of comments:
- I didn't invalidate your previous cache as I'm now using different kwargs in `download_and_transform` (additional xarray kwargs such as `combine` do not make much difference for this dataset, let's use the defaults)
- I try to avoid hardcoded stuff in the templates, such as the outliers removal you had in your notebook. I implemented a simple outlier removal, but this is just for the template. As always, you can adjust your notebook to suit your needs.
- I wasn't sure why you used resample with "YE". Because of that, when you make plots the years look shifted by one (but maybe that was on purpose?). I used groupby with `time.year`, is it OK? Or maybe you want to resample at a yearly frequency, but with years centered in December? If that's the case, we could use resample with 'AS-JUL'

Let me know!

**Comment by tdcwilliams** [comment]
Thanks @malmans2, the template looks good.
