### ISSUE TITLE
Ozone#1 MERGED-UV

### ISSUE THREAD

**Issue by sandrocalmanti** [bopen/c3s-eqc-toolbox-template#142]
### Notebook description

Dear @malmans2 ,

this is the first of two upcoming notebooks on Ozone. IT should be a rather simple one.

- Import data with two different transformation functions (full maps and regional slices, after converting the time dimension)
- Prepare a few plots (data coverage, time mean, annual cycle, and time series on regional slices).

It has been prepared by a collegue and I have tried clean it up a bit before your revision.

It's WP5

Best!

S.

### Notebook link or upload

[ozone-MERGED-UV.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/14785414/ozone-MERGED-UV.zip)

### Environment

<details>

</details>

**Comment by malmans2** [comment]
Hi @sandrocalmanti,

I think there's a bug with the data coverage figure:

1. The lat/lon sums have quite different values, and the cbar levels are not specified in your code. That means that the default colorbars are quite different for each subplot. However, the same colorbar is added to the figure.
2. Are the units correct? I only see a sum performed, but the the label says %

This is what I'm getting if I hardcode the same colorbar in your figures (don't worry about messy labels for now):
```python
fig, axs = plt.subplots(2, 1)
levels = range(0, 10_501, 1_500)
for ax, dim in zip(axs.flatten(), ("longitude", "latitude")):
    da = ds_map[varname].sum(dim, keep_attrs=True)
    da.plot.contourf(x="time", ax=ax, levels=levels, extend="max")
```
![image](https://github.com/bopen/c3s-eqc-toolbox-template/assets/22245117/5cbc8816-01fe-412e-9e3d-d2632c3f517a)

Questions for you:

1. Do you want to use the same colorbar for both subplots or on for each subplots? If the latter, we can just use the defaults, otherwise we can easily infer the min/max of both subplots.
2. Do you want to perform some rescaling (e.g., convert to percentage)?

**Comment by malmans2** [comment]
Hi @sandrocalmanti,

Besides for the issue in my previous comment, the notebook was already in great shape.
I made some minor change (e.g., units, labels, ...).

- Template: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/ozone_merged_uv.ipynb
- Notebook executed: https://gist.github.com/malmans2/88dc50e57033646b32156ead80213d87

Side node: Make sure you use the same chunking when you run `download_and_transform` on the same data but with different transform functions. Otherwise we download the data twice.

**Comment by malmans2** [comment]
Hi @sandrocalmanti,

I made some minor change. It should be in good shape now, but I'll wait for your OK to close this issue.

**Comment by sandrocalmanti** [comment]
Thank you @malmans2  we can close this NB. 

I will continue the work on [Ozone #2](https://github.com/bopen/c3s-eqc-toolbox-template/issues/143)
