### ISSUE TITLE
CMIP6: ensembe approach, regionalization, and bias statistics 

### ISSUE THREAD

**Issue by paololanteri** [bopen/c3s-eqc-toolbox-template#18]
Hi @malmans2 

I send you a new notebook that include some additional functionalities like:
-the creation of an ensemble of models
-the regionalization of the results
-some statistical analysis on the bias distribution
-plotting of taylor diagram for multimodel comparison

We discussed internally about interpolation and we decided to make the interpolation of the datasets after the postprocessing (temporal aggregation in this case) and just before the plotting. In our opinion this is the most scientifically appropriate procedure. That's why in this the notebook we put the regridding after the postprocessing.

I wait for your feedback, thank you!
Paolo

[scripts_v2.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/10827069/scripts_v2.zip)

**Comment by malmans2** [comment]
Hi @paololanteri ,

I haven't looked into all details of your notebooks yet, but I have a quick comment about interpolation and the use of ensambles.

I was going to implement some code to download and open multiple models using a single request chunked along the parameter `"model"`. That would return a single dataset with an additional dimension (e.g., dimension `"model":  {"model1", "model2", ...}`)

However, I realised that this is not possible without interpolating because different models have different coordinates.
Therefore, if interpolating each model before doing any processing is not accurate, the only solution I can see is that users write code using explicitly for loops (i.e., the same way you are doing it in your notebook).

**Comment by paololanteri** [comment]
Hi @malmans2,
thank you,
I agree with you, I can't see other ways to do it.

**Comment by malmans2** [comment]
Hi @paololanteri,
In the next couple of days I'm going to work on your code and see if I can add more diagnostics for your specific use case.

Is the zip file up-to-date, or did you make any progress with your notebook?
If the latter, could you please send me your latest notebook?

Thanks!

**Comment by paololanteri** [comment]
Hi @malmans2 ,
I will update you in the next hours
Than you,
Paolo

**Comment by malmans2** [comment]
OK, no rush.

FYI, inspired by your notebook I'm improving a little the caching of the `download_and_transform` function.
The previous version only allowed to apply transformations to each chunks.
That's not very useful when you need to perform operations on the whole dataset (e.g., time weighted means, ...), or when the final result is much smaller because there have been reductions along the chunked dimensions.

So I'm adding the argument `transform_chunks`.
* When True,`trasform_func` is applied to each chunk. That means that we cache the original data and all transformed chunks.
* When False,  `trasform_func` is applied to the dataset after concatenating all chunks, and it will store in the cache the original data and the final dataset.

If this sounds confusing, it should be much more clear once I send you some example (hopefully by tomorrow).

**Comment by paololanteri** [comment]
Hi @malmans2,
yes, very clear, thanks!
The notebook is still the same I sent you at the beginning of this page so let's go on with this.

Now we are working on a new one about temperature and precipitation trends, I will open a new issue soon.

**Comment by malmans2** [comment]
Hi @paololanteri ,
I haven't worked on the latest notebook yet, but I've updated the old wp4 template: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp4/clima_t2m.ipynb 
You'll see that it's using the argument `transform_chunks=False`.

Could you please test it when you get a chance?
Thanks!

**Comment by malmans2** [comment]
Hi @paololanteri ,
I made some progress. If you want to follow along, I'm working on this notebook: https://github.com/bopen/c3s-eqc-toolbox-template/blob/wp4-paolo/notebooks/wp4/wip.ipynb

I didn't get to the regionalization/analysis part yet, but I've revised the way you downloaded, resampled, and interpolated the results. If you try it, let me know how it goes.

I'll push more commits tomorrow.

**Comment by paololanteri** [comment]
Hi @malmans2, 
perfect, thank you,
tomorrow I will try it.

**Comment by paololanteri** [comment]
Hi @malmans2, 
after downloading the branch "wp4-paolo" and creating a new environment the notebook wip.ipynb works correctly!

**Comment by malmans2** [comment]
Hi @paololanteri,

I merged both notebook and code.

The notebook is ready for review. Please have a look and carefully check that all results are correct.
Here is the [clima_and_bias_pr_cmip6_regionalised.ipynb](https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp4/clima_and_bias_pr_cmip6_regionalised.ipynb).

A couple of comments:
1. You need to use the latest [c3s-eqc-automatic-quality-control](https://github.com/bopen/c3s-eqc-automatic-quality-control) as I added/changed some diagnostics
2. I haven't added `skillmetrics` to the environment yet. Let's wait and see if anyone else will need it. I will install it on the wp4 VM environment though. If you are working locally, you have to install it yourself.
3. I'm not useing `seaborn` so we don't add another dependency. The distribution plots with matplotlib look OK to me, but let me know if you'd like to use seaborn instead.

Let me know!

**Comment by malmans2** [comment]
I forgot to mention, it has been decided that the final result should be a notebook rather than a set of images.
Therefore, we don't need to save each figure anymore.

**Comment by malmans2** [comment]
Hi Paolo,
I'm closing this as there's a template for this under wp4, but feel free to re-open if anything is not right.
