### ISSUE TITLE
CMIP6 precipitation trend

### ISSUE THREAD

**Issue by paololanteri** [bopen/c3s-eqc-toolbox-template#23]
Hi @malmans2,
here a new notebook for the calcuation of trends,
Main tool is the calculation of trends using the Mann Kendall test, both for simple time series and also grid point by grid point, that is quite time demanding. 
I tried to include the hatches and stippling features in the attributes of plot.global_map() but unsuccesfully, so I used the more traditional way to plot with matplotlib in this notebook. Maybe you can help me to find a way to do this?
Some simple statistics are also include in functions_tmp.py

[scripts.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/10972023/scripts.zip)

**Comment by malmans2** [comment]
I'm exploring a few options for the trend computations.
Could you please give me an idea of the time it took to compute the trend maps in your notebook?

**Comment by paololanteri** [comment]
Hi @malmans2,
I didn't try yet the package you mentioned...

The computation of MK trend map for a 30 year period of monthly data at coarse resolution (250 km) took about 2 min, if I remember well. However, being proportional to the number of grid points it coud increase a lot for higher resolution grids.

**Comment by malmans2** [comment]
Got it.
Did you use coarse maps just as a temporary workaround, or is it OK to interpolate on a coarse grid?

I am making a few tests parallelizing with dask, but both with py and xarray-MannKendall it's going to take quite a bit if we interpolate on the ERA5 grid. Unfortunately, looks like we can't speed up pyMannKendall with numba.

**Comment by paololanteri** [comment]
On the native grid it would be the best. If not feasible we could also interpolate I thinnk, but we are still discussing internally about it.
In the meanwhile I've chosen an ensemble of low res models for this notebook.

**Comment by malmans2** [comment]
Hi @paololanteri,

Here is the notebook reviewed:
- [Template](https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp4/trend_pr_cmip6.ipynb)
- [Noetebook executed](https://github.com/bopen/c3s-eqc-toolbox-template/files/11151392/for_paolo.zip)

A few comments:
1. I was able to reduce the computation of trends to <20min for ERA5 and <1min for CMIP models. I'm using `xarrayMannKendall`. I'm able to reproduce `pymannkendall.original_test` using the following parameters: `alpha=0.05, method="theilslopes"`, but please double check that the trends are correct.
2. Everything gets cached, so I think it's not too bad timewise
3. If I understood correctly your plan, the best approach is to compute the trends on the original grid, then interpolate to ERA5 grid (I'm using conservative interpolation like you did). This is what I'm doing, and I believe this is why the statistics in my notebook are slightly different than yours.
4. Plotting takes more time compared to your notebook, that's because I'm plotting data interpolated to ERA5 grid, so quite bigger.
5. I tried also the models that you commented out in your notebook referring to some issues with bounds. It's all working ok with those models as well, I didn't include them just to facilitate the comparison with your results.
6. I think there is a setting you have to play with (or a bug) in `skill_metrics.taylor_diagram`. You don't see it in this notebook, but if you add 2 or more models to the analysis, it throws an error (something to do with colors). I'm not familiar with the library, so maybe is an easy fix for you (not sure if you can pass the list of colors or a discrete colorbar).

As usual, please check everything and make sure everything is working as expected.
Let me know if anything doesn't look right!

**Comment by paololanteri** [comment]
Thank you Mattia,
I confirm everything you're saying, thank you! I will check as soon as possible.
Concerning point 6, we also noticed this problem in the previous notebooks, but we didn't find an easy solution at that time. I will try to find a workaround for this.

**Comment by malmans2** [comment]
OK, looks like a bug but let's see what the maintainers think about it.

See: https://github.com/PeterRochford/SkillMetrics/issues/37, https://github.com/PeterRochford/SkillMetrics/pull/38

**Comment by malmans2** [comment]
Hi @paololanteri,

FYI I made a big refactor to handle better weighted diagnostics. I checked your notebook templates, and I think everything is working as expect. Please try it out whenever you get a chance.

I also made a couple of API changes (sorry, I bit annoying but I think it's much clearer now). I've updated your templates, so they're already using the new API:
1. `time_weighted_mean`: performs time weighted mean, therefore there's no time dimension in the output
2. `annual_weighted_mean`: returns annual weighted means, therefore the output time dimension is `year`

**Comment by paololanteri** [comment]
Hi @malmans2,
I've run the last version of the notebook. 
I think everything is ok, thank you!
I would just add a caption to the images explaining how the significance is calculated (in both cases: ensemble and single-model). But I can do it.
Thank you,
Paolo

**Comment by malmans2** [comment]
Great, thanks!
Feel free to add captions and send me the updated notebook (or open a PR). Keep in mind that in this repo we only have templates, not the actual deliverable and/or evaluation.

BTW, looks like the maintainers of SkillMetrics are not very responsive.
We might have to write our own taylor diagram functions if you need to show more models.
Please open a dedicated issue if you think we should implement it.

Have a good weekend!
