### ISSUE TITLE
Jupyter Notebook for the LULC dataset - to be reviewed and optimised w/ eqc toolbox

### ISSUE THREAD

**Issue by anolive** [bopen/c3s-eqc-toolbox-template#26]
Dear B-OPEN team,

As agreed previously, please find here attached the First Use Case/User Question for the Land Use/Land Cover catalogue entry (this one: https://cds.climate.copernicus.eu/cdsapp#!/dataset/satellite-land-cover?tab=overview).

We are currently using cdsapi and our go-to libraries in handling this type of dataset, but hopefully, it won't be too much of a hassle for you to reshape it into the toolbox.

Let us know your feedback on this.
Ana

[C3S2_D520.5.3.2_Quality_Assessment_User_Questions_LULC_UQ1_v1.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/10999503/C3S2_D520.5.3.2_Quality_Assessment_User_Questions_LULC_UQ1_v1.zip)

**Comment by malmans2** [comment]
Hi @anolive,

I'll work on it next week and I'll probably add a few diagnostics for your use case.

In the mean time, here is how you can replace the whole first section.
```python
from c3s_eqc_automatic_quality_control import download, utils

# Time
year_start = 2019
year_stop = 2020

# Region of interest
lon_slice = slice(-10, 0)
lat_slice = slice(45, 35)

# Download and transform (cached)
request = (
    "satellite-land-cover",
    {
        "variable": "all",
        "format": "zip",
        "version": "v2.1.1",
        "year": [str(year) for year in range(year_start, year_stop + 1)],
    },
)
ds = download.download_and_transform(
    *request,
    chunks={"year": 1},
    transform_func=utils.regionalise,
    transform_func_kwargs={"lon_slice": lon_slice, "lat_slice": lat_slice},
)

```
The code above is downloading yearly data and extracting a region, returning a single (chunked) dataset.

**Comment by anolive** [comment]
Hi there! Thanks for your feedback, we will test this and let you know.

**Comment by malmans2** [comment]
Hi @anolive,

I see you hardcoded various variables defining colors.
Are those defined in some official document?
If yes, could you please share the links/files?
Maybe they are parsable and we can get it directly from those documents.

**Comment by malmans2** [comment]
Actually, exploring the dataset I see they are already defined in the metadata. 
Can we use those value?
![image](https://user-images.githubusercontent.com/22245117/226302882-11f462e3-aa65-453e-8450-de59569fb72c.png)

**Comment by malmans2** [comment]
I implemented the `plot.lccs_map`. 
You can pass a dictionary mapping `{meaning: (color, flags)}`, otherwise everything is inferred from the metadata.

To test, you need to use this branch: https://github.com/bopen/c3s-eqc-automatic-quality-control/tree/ana
If you already have an environment up to date, you can install the branch using the following command:
```
pip install git+https://github.com/bopen/c3s-eqc-automatic-quality-control.git@ana
```

Here is an example:
[wip.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/11022152/wip.zip)

**Comment by malmans2** [comment]
Hi @anolive,

I've finished to work on your notebook. I've added a notebook in the templates directory to show how to use the plotting functions for your use case.The new functions are named: `plot.lccs_map` and `plot.lccs_bar`. They are self-documented (i.e., look at python's `help` function), but if you have any question feel free to shoot me a message.

I've already merged all branches, so it should be easier for you to test. I've also updated the VM environments.

I made a little change to your last plot. Instead of defining a threshold, I'm using stacked bars. Let me know if that's OK. Now it looks like this:
![bars1](https://user-images.githubusercontent.com/22245117/226585333-18462c4a-51c4-4409-be8d-a8ef7bc638a9.png)
More, generally, you can also do this:
![bars2](https://user-images.githubusercontent.com/22245117/226585554-b0e95528-2674-49b6-b93d-f3dae4cf6358.png)

You can find the notebook [here](https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/satellite/C3S2_D520.5.3.2_Quality_Assessment_User_Questions_LULC_UQ1_v1.ipynb).
The code is [here](https://github.com/bopen/c3s-eqc-automatic-quality-control/blob/c589db3477785137d232ff9d2078341c13e198a7/c3s_eqc_automatic_quality_control/plot.py#L240-L387). 
I'm also attaching the [notebook executed](https://github.com/bopen/c3s-eqc-toolbox-template/files/11027513/for_ana.zip).

Let me know your thoughts!

**Comment by anolive** [comment]
Dear Mattia, Sorry for the late reply!

Thank you very much for your editions and suggestions, this looks great. The plots also work quite nice.

We will look into this today in the next few days to update the notebook accordingly.
I'll leave this open just to give you feedback.
Thank you.

**Comment by malmans2** [comment]
Perfect, no rush from my side.
Just a couple requests:
1. Let me know if the IPCC spec for colors is publicly available and send me the link. It would be better to parse it rather than hardcode it.
2. Are you wp3, 4, or 5? I'll move the notebook to the dedicated folder.

**Comment by anolive** [comment]
Great. We're (+ATLANTIC) are on WP5. :)
We couldn't find any official colour scheme; thus, we choose one. We will give another try to see if we can find something.

**Comment by malmans2** [comment]
The template is now here: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/LULC_classification_reliability.ipynb

One more thing I forgot to ask, when you are all set, please let me know the request that you are going to run. I'm building scripts to pre-populate the cache, so you'll always find most of the data that you need on the VM.

**Comment by malmans2** [comment]
Closing - as always, feel free to re-open!
