### ISSUE TITLE
[WP5] ERA5 diagnostics - zonal average

### ISSUE THREAD

**Issue by sandrocalmanti** [bopen/c3s-eqc-toolbox-template#45]
### Describe the solution you'd like

Dear Mattia,

with this notebook
[zonal_mean.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/11272123/zonal_mean.zip)

I'm trying to reproduce figures 2 and 3 of this document

[C3S_D511.4.1b1_202006_SPQB_Temperature (upper air)_ERA5_T.pdf](https://github.com/bopen/c3s-eqc-toolbox-template/files/11272125/C3S_D511.4.1b1_202006_SPQB_Temperature.upper.air._ERA5_T.pdf)

A couple of comments and requests.

1.   The **Download data** and transform seems to work correctly and it's now in the cache so it runs quickly. However, the first computation was quite slow and I was receiving warnings indicating the need for renaming the longitude dimension. The data is in the cache so it should run smoothly. However, I had to define a simple trasnformation function `zonal_mean`  and problably this is not done properly so it slows down everythig. The computation of the zonal mean is a basic operation and it might be considered appropriate for the `diagnostic` package.
2. I have a problem in the section **Compute monthly climatology in zonal regions**.  I need to compute a weighted average over a certain zonal region and then group it by month to compute the monthly climatology. This doesn't seems to work with the methods associated to xarray objects (I did a quick search on this) so I have tried to apply the weights directly to the variable in the DataArray and the select the region I want to focus on. I get a reasonable pattern (compare the last figure in the notebook with Figure 3 in the document), but the values are not correct and although I'm expecting that xarray interprets the name of dimensions when multiplying xr objects, I might have used the wrong syntax. Can you help with that?

Cheers

Sandro

**Comment by malmans2** [comment]
Hi @sandrocalmanti,

> The first computation was quite slow

If it's reasonably slow, I think that's OK. But if you think that it gets really too slow, we can try to play a bit more with chunking (e.g., we can use larger time chunks to reduce I/O).

> I was receiving warnings indicating the need for renaming the longitude dimension

Don't worry about the warnings for now, they're triggered by the harmoniser developed by ECMWF (I've already reported it to Eddy, the warnings will eventually disappear).

> However, I had to define a simple trasnformation function zonal_mean and problably this is not done properly so it slows down everythig. 

Good point, I'll add a zonal mean function. Your function looks OK to me. My only comment is that you lost all attributes, so things like units and long names are not displayed in the plot. For example, you can use [`xr.set_options`](https://docs.xarray.dev/en/stable/generated/xarray.set_options.html) or `ds.mean("longitude", keep_attrs=True)`

> I have a problem in the section Compute monthly climatology in zonal regions.

In principle, you could use our `diagnostics.spatial_weighted_mean` here. But you can NOT at the moment because by default we also use `longitude` to compute weights (see [here](https://github.com/bopen/c3s-eqc-automatic-quality-control/blob/0b57a569829bf3a5cc7f30a20115a3e5a503b1e7/c3s_eqc_automatic_quality_control/diagnostics.py#L32-L38)). I'm going to add an option to ignore longitude, so you'll be able to do this: `diagnostics.spatial_weighted_mean(ds, use_lon=False)`.

In the meantime, if you want to play with xarray's weighted objects, this is how you could do it:
```python
import calendar

with xr.set_options(keep_attrs=True):
    ds_monthly = ds.groupby("time.month").mean()
    ds_sel = ds_monthly.sel(latitude=slice(90, 60))
    weights = np.cos(np.deg2rad(ds_monthly["latitude"]))
    ds_weighted = ds_sel.weighted(weights).mean("latitude")

ds_weighted["level"].attrs.update({"long_name": "Level", "units": "hPa"})
ds_weighted["t"].plot.contourf(
    x="month",
    yscale="log",
    levels=range(180, 301, 15),
    yincrease=False,
    figsize=(10, 10),
    cmap="YlOrRd",
    cbar_kwargs={"orientation": "horizontal"},
)
yticks = [1000, 500, 100, 10, 1]
plt.yticks(yticks, yticks)
plt.xticks(range(1, 13), list(calendar.month_abbr)[1:])
plt.xlabel(None)
plt.title("ERA5 temperature on pressure levels [60°N - 90°N]")

```
![image](https://user-images.githubusercontent.com/22245117/233091211-7051cc30-fd95-4f72-8875-e8fba43abb74.png)

I'll add a template for this use case and will let you know when it's ready!

**Comment by malmans2** [comment]
I'll close this when I add the template

**Comment by malmans2** [comment]
Hi @sandrocalmanti,

I've been giving some thoughts to this, and I think it's better if you define yourself a function to compute and cache zonal mean. The reason is that it's a very simple operation that does not require weighting, therefore it's better if users understand and learn how to do this (it's also a good example to show how to implement custom cached functions).

I've updated the [template](https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/anom_time_pressure.ipynb), so it now computes and caches the zonal mean first, then the spatial weighted means.

I'm closing this, but feel free to re-open if you think it's better to implement the `zonal_mean` in `c3s_eqc_automatic_quality_control`.
