### ISSUE TITLE
Working with seasonal_std

### ISSUE THREAD

**Issue by sandrocalmanti** [bopen/c3s-eqc-toolbox-template#57]
### Describe the solution you'd like

Hi @malmans2 I'm working with this notebook

[ERA5_stormtrack.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/11533244/ERA5_stormtrack.zip)

to compute and map the seasonal mean and standard deviation of the 500hPa geopotential height. The `mean` works fine.
With the `std` either the notebook remains idle for hours, or it dies after a few seconds.

Is there any issue with the required memory?

Cheers

S.

**Comment by malmans2** [comment]
Hi @sandrocalmanti,
I'll take a look ASAP.

In the last couple of weeks there have been 5-10 users connect to the VM at the same time. It's possible that the VM is not able to handle it. If that's the case, there's not much I can do about it and we need to discuss a better strategy with Chunxue.

I'll be in touch.

**Comment by malmans2** [comment]
Hi @sandrocalmanti,

The VM is a bit stressed, but also there's a couple of fixes in your notebook that should make it work:
1. You've been computing seasonal weighted mean on daily data. It's computationally more expensive, but I think it's also incorrect as the default weights are meant to be used with monthly data. I believe you don't need to weight the time reduction, so you can pass the argument `weights=False`
2. Dividing the request in smaller chunks seems to work much better. It's also useful because if you'll need in the future more times, you can re-use cached raw data.

Here is a snippet:
```python
import cartopy.crs as ccrs
import matplotlib.pyplot as plt
import xarray as xr
from c3s_eqc_automatic_quality_control import diagnostics, download, plot

plt.style.use("seaborn-v0_8-notebook")

# Select time period and chunks
start = "1980"
stop = "1989"  # None: present
chunks = {"year": 1, "time": 1}

# Define request
collection_id = "reanalysis-era5-pressure-levels"
request = {
    "product_type": "reanalysis",
    "format": "grib",
    "variable": "geopotential",
    "pressure_level": "500",
    "area": [90, -180, 30, 180],
    "time": ["00:00", "12:00"],
}
requests = download.update_request_date(request, start=start, stop=stop)

# Download, transform, and store mean and std in the same dataset
dataarrays = []
for reduction in ("mean", "std"):
    transform_func = getattr(diagnostics, f"seasonal_weighted_{reduction}")
    ds = download.download_and_transform(
        collection_id,
        requests,
        transform_func=transform_func,
        transform_func_kwargs={"weights": False},
        chunks=chunks,
        transform_chunks=False,
        concat_dim="forecast_reference_time",
        combine="nested",
    )
    dataarrays.append(ds["z"].rename(reduction))
ds = xr.merge(dataarrays)

# Plot projected maps of seasonal means
plot.projected_map(
    ds["mean"], projection=ccrs.Robinson(), col="season", col_wrap=2, robust=True
)
```
![image](https://github.com/bopen/c3s-eqc-toolbox-template/assets/22245117/1cbf92e7-d9bb-4919-a3f0-dc3a46ce3397)

I think this issue is resolved, as always feel free to re-open it though.
