### ISSUE TITLE
ERA5-Land temperature revision 2

### ISSUE THREAD

**Issue by Cri-dei** [bopen/c3s-eqc-toolbox-template#87]
### Notebook description

Rewiew of the notebook:
1. Please use color-blind friendly palettes for the contour plot. More info are available from [Seaborn]. Also see (and suggest changes if needed) the [COP1-col] and [NOAA-col] files, as they provide suitable examples for different ECVs.
[COP1_color_lookup_table_19_03_2019.docx](https://github.com/bopen/c3s-eqc-toolbox-template/files/12146345/COP1_color_lookup_table_19_03_2019.docx)

They suggest priority to the Cop1-col file in the refs (I attached here the doc file), if the variable is listed

2. Add trend line in the last plot. (I did it but maybe the code is naive)

### Notebook link or upload

[ERA-5Land_Temperature_rev2.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/12146322/ERA-5Land_Temperature_rev2.zip)

### Environment

<details>

</details>

**Comment by malmans2** [comment]
Which colormap do you want to use?

**Comment by Cri-dei** [comment]
The variable called "tas" in the document I attached:   "tas": dict({"Data": "YlOrRd", "Sequential":"Wistia",                  "Diverging":"RdBu_r"}). (They give this document as reference for the palette)

**Comment by malmans2** [comment]
OK, `YlOrRd` then.

For the trend, are you sure you want to use a simple linear trend rather than the slope/intercept already computed using MannKendall?

**Comment by Cri-dei** [comment]
Ya you right the Mann Kendall is better.

**Comment by malmans2** [comment]
All set: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/era5_land_temperature.ipynb

Let me know if everything is OK.

**Comment by Cri-dei** [comment]
Perfect! We can close it, thanks!

**Comment by Cri-dei** [comment]
I add a comment here about the shapefile of Europe that we are using for some notebooks.
"Shapefile is coming from figshare ‘shapefile_url’, to be checked if this is ok or blocked from CDS servers. A possible alternative (NUTS) is already available in the CDS (https://cds.climate.copernicus.eu/toolbox/doc/tools/cdstoolbox.eurostat.nuts.html).
There's a downloading step to the figshare repository, unless I am wrong. C3S has no control on data outside of the CDS and access may be blocked". They told me to discuss it with you, if this can be a problem

**Comment by malmans2** [comment]
I think it's too early to discuss these details, so I wouldn't worry too much about it right now.
For the time being it's not an issue to access external data, especially if it's just a shapefile.

However, if NUTS suits your needs, I think it might be a better alternative. It's already used in a few notebooks developed by other evaluators, and it's accessed from their website rather than figshare.

See:

- [‎notebooks/wp5/FIRE_burned_area.ipynb](https://github.com/bopen/c3s-eqc-toolbox-template/blob/d9cbef6a62e5cb758ce07b24a58e50c2ee820dda/notebooks/wp5/FIRE_burned_area.ipynb#L60)
- [‎notebooks/wp5/LUCL_land_cover_classification_reliability.ipynb](https://github.com/bopen/c3s-eqc-toolbox-template/blob/d9cbef6a62e5cb758ce07b24a58e50c2ee820dda/notebooks/wp5/LUCL_land_cover_classification_reliability.ipynb#L62)
