### ISSUE TITLE
ERA5 on single level - Variability

### ISSUE THREAD

**Issue by Yassminaa** [bopen/c3s-eqc-toolbox-template#89]
### Notebook description

'Variability' diagnostics of the 2-meter temperature of ERA5 on a single level

### Notebook link or upload

[UC2_ERA5_t2m_anomaly.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/12226449/UC2_ERA5_t2m_anomaly.zip)

### Environment

<details>

**Comment by malmans2** [comment]
Hi @Yassminaa,

Here is the template: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/era5_t2m_variability.ipynb
Here is the template executed: https://gist.github.com/malmans2/ba3656f6db305c8d33208d84e7356aa6

You've been using monthly chunks in your notebooks, which is not a good choice for this kind of data.
It produces ~1000 requests and therefore a lot of small files. It's not a good choice because that many small files are going to slow you down. Furthermore, other evaluators have been using the same dataset with yearly chunks, therefore you duplicated the raw data cached on the VM.

As usual, please let me know if everything works OK and we can close this issue.

**Comment by malmans2** [comment]
Hi @Yassminaa,

Can we close this or are you still working on it?
