### ISSUE TITLE
Problem with CMIP6 global plots for single models 

### ISSUE THREAD

**Issue by paololanteri** [bopen/c3s-eqc-toolbox-template#91]
### What happened?

Hi Mattia,
We modified the trend and the clima_and_bias notebooks, adding comments and making small variations to the code.
In particular we implemented a new set of conditions to treat the significance of ensemble results, according to IPCC guidance.  

I want to ask you two things:
1) We are encountering a problem plotting global results for single models in the facet plot, for both notebooks: the maps are anomalously cutted both at poles and at longitude boundaries.

2) We would like to change the label for the ensemble from "model = CMIP6 " to "CMIP6 ensemble".  Same for CORDEX. I think that we can, in general, remove the statement "model =" from all the titles, keeping just the name of the dataset. 

I attach the latest version of the notebook I'm working on.
[trend_cmip6_t2m_annual_v2.ipynb.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/12239131/trend_cmip6_t2m_annual_v2.ipynb.zip)

Thank you

### Environment

<details>

</details>

**Comment by malmans2** [comment]
Hi @paololanteri,

> We are encountering a problem plotting global results for single models in the facet plot, for both notebooks: the maps are anomalously cutted both at poles and at longitude boundaries.

Fixed. Looks like we need to use `set_global` rather than `set_extent` for global maps.

> We would like to change the label for the ensemble from "model = CMIP6 " to "CMIP6 ensemble". Same for CORDEX. I think that we can, in general, remove the statement "model =" from all the titles, keeping just the name of the dataset.

Done.

Could you please check whether the latest templates work OK?
These are the changes I made: https://github.com/bopen/c3s-eqc-toolbox-template/commit/37fbdf92548d46ead1b95cf76992c33013af1ecf

> We modified the trend and the clima_and_bias notebooks, adding comments and making small variations to the code.
In particular we implemented a new set of conditions to treat the significance of ensemble results, according to IPCC guidance.

When you are done editing the notebooks, could you please open a PR or share the latest version. Make sure the latest changes are also implemented in the notebooks.

**Comment by paololanteri** [comment]
Hi Mattia,
yes, it is fixed, 
thank you
Paolo
